// Flutter app module Gradle (Kotlin DSL).
// Generated by `flutter create` at first run; this file pre-seeds the deps
// the widget + geofence work needs so Android Studio compiles cleanly.
//
// IMPORTANT: this file may need a regenerate pass after `flutter create .`
// in this directory — preserve the `dependencies { ... }` and
// `defaultConfig.applicationId` blocks below.

plugins {
    id("com.android.application")
    id("kotlin-android")
    // The Flutter Gradle Plugin must be applied after the Android & Kotlin
    // Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
}

android {
    namespace = "com.molcube.workmanager"
    compileSdk = 35

    defaultConfig {
        applicationId = "com.molcube.workmanager"
        minSdk = 24            // Android 7.0 — covers ~99% of devices in 2026
        targetSdk = 35
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        isCoreLibraryDesugaringEnabled = true
    }
    kotlinOptions { jvmTarget = "17" }

    buildFeatures {
        compose = true
    }
    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.14"
    }

    buildTypes {
        release {
            // Replace with the production signingConfig before shipping.
            signingConfig = signingConfigs.getByName("debug")
        }
    }
}

flutter {
    source = "../.."
}

dependencies {
    // Glance home-screen widgets
    implementation("androidx.glance:glance-appwidget:1.1.0")
    implementation("androidx.glance:glance-material3:1.1.0")

    // DataStore — bridges Flutter MethodChannel writes → widget reads
    implementation("androidx.datastore:datastore-preferences:1.1.1")

    // Background tasks (geofence periodic poll registered from Dart via
    // the workmanager plugin)
    implementation("androidx.work:work-runtime-ktx:2.9.1")

    // Coroutines
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1")

    // Geofencing client
    implementation("com.google.android.gms:play-services-location:21.3.0")

    // Java 8+ desugaring (java.time.* on minSdk < 26)
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.2")
}
