# Generated by Django 5.1.4 on 2026-05-03 18:15

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_date', models.DateField()),
                ('clock_in_at', models.DateTimeField(blank=True, null=True)),
                ('clock_out_at', models.DateTimeField(blank=True, null=True)),
                ('clock_in_kind', models.CharField(blank=True, choices=[('OFFICE', 'Office'), ('WFH', 'WFH'), ('MANUAL', 'Manual')], default='', max_length=8)),
                ('is_late', models.BooleanField(default=False)),
                ('is_early_leave', models.BooleanField(default=False)),
                ('total_break_minutes', models.IntegerField(default=0)),
                ('total_work_minutes', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('WORKING', 'Working'), ('ON_BREAK', 'On break'), ('COMPLETED', 'Completed')], default='WORKING', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'attendance_record',
            },
        ),
        migrations.CreateModel(
            name='BreakRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'break_record',
            },
        ),
        migrations.CreateModel(
            name='OvertimeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_date', models.DateField()),
                ('requested_minutes', models.IntegerField()),
                ('reason', models.TextField(blank=True, default='')),
                ('auto_generated', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'overtime_request',
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.TimeField(default='09:00')),
                ('end_time', models.TimeField(default='18:00')),
                ('break_minutes', models.IntegerField(default=60)),
                ('work_days', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'work_schedule',
            },
        ),
    ]
