# Generated by Django 5.1.4 on 2026-05-03 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='clock_in_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='identity.location'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.company'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='identity.membership'),
        ),
        migrations.AddField(
            model_name='breakrecord',
            name='attendance_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='attendance.attendancerecord'),
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.company'),
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_overtimes', to='identity.membership'),
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_requests', to='identity.membership'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='membership',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='identity.membership'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['company', 'work_date'], name='idx_att_company_date'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['company', 'status'], name='idx_att_status'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('membership', 'work_date'), name='uniq_member_workdate'),
        ),
        migrations.AddIndex(
            model_name='overtimerequest',
            index=models.Index(fields=['company', 'status'], name='idx_ot_company_status'),
        ),
        migrations.AddIndex(
            model_name='overtimerequest',
            index=models.Index(fields=['membership', 'work_date'], name='idx_ot_member_date'),
        ),
    ]
