# Generated by Django 5.1.4 on 2026-05-03 18:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('IOS', 'iOS'), ('ANDROID', 'Android'), ('WEB', 'Web'), ('DESKTOP', 'Desktop')], max_length=16)),
                ('token', models.CharField(max_length=512)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to='identity.membership')),
            ],
            options={
                'db_table': 'device_token',
                'constraints': [models.UniqueConstraint(fields=('platform', 'token'), name='uniq_platform_token')],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_kind', models.CharField(max_length=64)),
                ('channel', models.CharField(max_length=16)),
                ('payload_json', models.JSONField(default=dict)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='identity.membership')),
            ],
            options={
                'db_table': 'notification_log',
                'indexes': [models.Index(fields=['membership', 'read_at'], name='idx_notif_member_unread')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('PUSH', 'Push'), ('EMAIL', 'Email'), ('INAPP', 'In-app')], max_length=16)),
                ('event_kind', models.CharField(max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to='identity.membership')),
            ],
            options={
                'db_table': 'notification_preference',
                'constraints': [models.UniqueConstraint(fields=('membership', 'channel', 'event_kind'), name='uniq_notif_pref')],
            },
        ),
    ]
