# Generated by Django 5.1.4 on 2026-05-03 19:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_user_totp_enabled_user_totp_secret_recoverycode'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('PUSH', 'Push'), ('EMAIL', 'Email'), ('INAPP', 'In-app')], max_length=16)),
                ('event_kind', models.CharField(max_length=64)),
                ('payload_json', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('DEAD', 'Dead')], default='PENDING', max_length=16)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=5)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_error', models.TextField(blank=True, default='')),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_outbox', to='identity.membership')),
            ],
            options={
                'db_table': 'notification_outbox',
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='idx_outbox_status_next')],
            },
        ),
    ]
