# Generated by Django 5.1.4 on 2026-05-03 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approval', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaltask',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_inbox', to='identity.membership'),
        ),
        migrations.AddField(
            model_name='approvaltask',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.company'),
        ),
        migrations.AddField(
            model_name='approvaltask',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='identity.membership'),
        ),
        migrations.AddIndex(
            model_name='approvaltask',
            index=models.Index(fields=['approver', 'status'], name='idx_appr_approver_status'),
        ),
        migrations.AddIndex(
            model_name='approvaltask',
            index=models.Index(fields=['company', 'status'], name='idx_appr_company_status'),
        ),
    ]
