# Generated by Django 5.1.4 on 2026-05-03 18:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_from', models.DateField()),
                ('rules_json', models.JSONField(default=dict)),
                ('expiry_months', models.IntegerField(default=12)),
                ('notify_days_before', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_policies', to='identity.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='identity.membership')),
            ],
            options={
                'db_table': 'leave_policy',
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('GRANTED', 'Granted'), ('USED', 'Used'), ('EXPIRED', 'Expired'), ('ADJUSTED', 'Adjusted')], max_length=16)),
                ('days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('granted_at', models.DateField()),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('related_request_id', models.UUIDField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.company')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='identity.membership')),
            ],
            options={
                'db_table': 'leave_balance',
                'indexes': [models.Index(fields=['membership', 'kind'], name='idx_balance_member_kind')],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('kind', models.CharField(choices=[('FULL', 'Full day'), ('AM_HALF', 'AM half'), ('PM_HALF', 'PM half')], default='FULL', max_length=16)),
                ('days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.company')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_leaves', to='identity.membership')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='identity.membership')),
            ],
            options={
                'db_table': 'leave_request',
                'indexes': [models.Index(fields=['membership', 'status'], name='idx_leave_req_member_status'), models.Index(fields=['company', 'start_date', 'end_date'], name='idx_leave_req_range')],
            },
        ),
    ]
