#!/usr/bin/env node
/**
 * gen_tokens.mjs — B-NAT-01 (ADR-007 사전 작업)
 *
 * Reads `apps/web/src/shared/styles/tokens.css` (CSS variables) and emits
 * `apps/mobile/lib/theme/tokens.g.dart` (Flutter ColorScheme + spacing/radii
 * helpers). Single source of truth = the CSS file.
 *
 * Usage:
 *   node apps/mobile/tools/gen_tokens.mjs
 *
 * Output:
 *   apps/mobile/lib/theme/tokens.g.dart  — auto-generated, do not edit.
 *
 * Coverage:
 *   - Brand + grey + semantic (success/warn/caution/danger/info/purple) colors
 *   - Status (--s-*) aliases
 *   - Radii (--r-xs..pill) → BorderRadius
 *   - Spacing (--sp-*) → double constants
 *   - Motion durations → Duration constants
 *   - Skip themes (dark/mint/violet/coral) for v0 — Flutter dark mode is
 *     handled by separate ThemeData; this codegen focuses on light tokens.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..", "..", "..");
const cssPath = join(repoRoot, "apps", "web", "src", "shared", "styles", "tokens.css");
const outDir = join(repoRoot, "apps", "mobile", "lib", "theme");
const outPath = join(outDir, "tokens.g.dart");

const css = readFileSync(cssPath, "utf8");

/** Extract :root { ... } block (light theme baseline). */
const rootMatch = css.match(/:root\s*\{([\s\S]*?)\}/);
if (!rootMatch) {
  console.error("Could not find :root { ... } block in tokens.css");
  process.exit(2);
}
const rootBody = rootMatch[1];

/** Parse `--name: value;` pairs, resolving `var(--ref)` one level. */
const vars = new Map();
const decls = rootBody.match(/--[a-z0-9-]+\s*:\s*[^;]+;/g) ?? [];
for (const line of decls) {
  const m = line.match(/(--[a-z0-9-]+)\s*:\s*([^;]+);/);
  if (!m) continue;
  vars.set(m[1], m[2].trim());
}

/** Resolve `var(--x)` references — single-level deep is enough for our tokens. */
function resolve_(value) {
  const ref = value.match(/var\((--[a-z0-9-]+)\)/);
  if (!ref) return value;
  const target = vars.get(ref[1]);
  if (!target) return value;
  return target.match(/var\(/) ? resolve_(target) : target;
}

/** Convert #RRGGBB | rgba(...) → Flutter Color(0xAARRGGBB). */
function toDartColor(value) {
  const v = resolve_(value).trim();
  if (v.startsWith("#")) {
    const hex = v.slice(1);
    if (hex.length === 6) return `const Color(0xFF${hex.toUpperCase()})`;
    if (hex.length === 8)
      return `const Color(0x${hex.slice(6, 8)}${hex.slice(0, 6)}.toUpperCase())`;
  }
  const rgba = v.match(/rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)(?:\s*,\s*([0-9.]+))?\s*\)/i);
  if (rgba) {
    const [, r, g, b, a] = rgba;
    const alpha = Math.round((a !== undefined ? Number(a) : 1) * 255)
      .toString(16)
      .padStart(2, "0");
    const toHex = (n) => Number(n).toString(16).padStart(2, "0");
    return `const Color(0x${alpha}${toHex(r)}${toHex(g)}${toHex(b)}.toUpperCase())`;
  }
  return null;
}

const COLOR_KEYS = [
  "--brand",
  "--brand-hover",
  "--brand-soft",
  "--brand-softer",
  "--brand-text",
  "--grey-900",
  "--grey-800",
  "--grey-700",
  "--grey-600",
  "--grey-500",
  "--grey-400",
  "--grey-300",
  "--grey-200",
  "--grey-100",
  "--grey-50",
  "--white",
  "--success",
  "--success-soft",
  "--warn",
  "--warn-soft",
  "--caution",
  "--caution-soft",
  "--danger",
  "--danger-soft",
  "--info",
  "--info-soft",
  "--purple",
  "--purple-soft",
];

const STATUS_KEYS = ["--s-office", "--s-wfh", "--s-leave", "--s-break", "--s-off"];

const RADII = {
  rXs: "--r-xs",
  rSm: "--r-sm",
  rMd: "--r-md",
  rLg: "--r-lg",
  rXl: "--r-xl",
  rPill: "--r-pill",
};

const SPACING = {
  sp1: "--sp-1",
  sp2: "--sp-2",
  sp3: "--sp-3",
  sp4: "--sp-4",
  sp5: "--sp-5",
  sp6: "--sp-6",
  sp8: "--sp-8",
  sp10: "--sp-10",
  sp12: "--sp-12",
};

const MOTION = {
  motionInstant: "--motion-instant",
  motionFast: "--motion-fast",
  motionStandard: "--motion-standard",
  motionSlow: "--motion-slow",
  motionPage: "--motion-page",
};

function snakeToCamel(name) {
  return name
    .replace(/^--/, "")
    .replace(/-(\w)/g, (_, ch) => ch.toUpperCase());
}

function numericPx(value) {
  const m = resolve_(value).match(/(-?\d+(?:\.\d+)?)px/);
  return m ? Number(m[1]) : null;
}

function numericMs(value) {
  const m = resolve_(value).match(/(-?\d+(?:\.\d+)?)ms/);
  return m ? Number(m[1]) : null;
}

const lines = [];
lines.push("/// AUTO-GENERATED by tools/gen_tokens.mjs from");
lines.push("/// apps/web/src/shared/styles/tokens.css — DO NOT EDIT.");
lines.push("/// Regenerate via: `node apps/mobile/tools/gen_tokens.mjs`.");
lines.push("///");
lines.push("/// B-NAT-01 (ADR-007): single source of truth = CSS variables.");
lines.push("/// Phase A native pages should import from `tokens.g.dart` to keep");
lines.push("/// WebView/Web SPA + native UI visually consistent.");
lines.push("library;");
lines.push("");
lines.push("import 'package:flutter/material.dart';");
lines.push("");
lines.push("class WMTokens {");
lines.push("  WMTokens._();");
lines.push("");
lines.push("  // ───────────── Colors ─────────────");
for (const key of COLOR_KEYS) {
  const value = vars.get(key);
  if (!value) continue;
  const dart = toDartColor(value);
  if (!dart) continue;
  const name = snakeToCamel(key);
  lines.push(`  static const Color ${name} = ${dart.replace("const ", "")};`);
}
lines.push("");
lines.push("  // ───────────── Status aliases ─────────────");
for (const key of STATUS_KEYS) {
  const value = vars.get(key);
  if (!value) continue;
  const dart = toDartColor(value);
  if (!dart) continue;
  const name = snakeToCamel(key);
  lines.push(`  static const Color ${name} = ${dart.replace("const ", "")};`);
}
lines.push("");
lines.push("  // ───────────── Radii (px) ─────────────");
for (const [name, key] of Object.entries(RADII)) {
  const value = vars.get(key);
  if (!value) continue;
  const n = numericPx(value);
  if (n === null) continue;
  lines.push(`  static const double ${name} = ${n}.0;`);
}
lines.push("");
lines.push("  // ───────────── Spacing (px) ─────────────");
for (const [name, key] of Object.entries(SPACING)) {
  const value = vars.get(key);
  if (!value) continue;
  const n = numericPx(value);
  if (n === null) continue;
  lines.push(`  static const double ${name} = ${n}.0;`);
}
lines.push("");
lines.push("  // ───────────── Motion (Duration) ─────────────");
for (const [name, key] of Object.entries(MOTION)) {
  const value = vars.get(key);
  if (!value) continue;
  const ms = numericMs(value);
  if (ms === null) continue;
  lines.push(`  static const Duration ${name} = Duration(milliseconds: ${ms});`);
}
lines.push("}");
lines.push("");
lines.push("/// Material 3 ColorScheme derived from WMTokens. Mirrors the web app's");
lines.push("/// brand-blue + warm-grey palette. Phase A pages use this as their");
lines.push("/// `MaterialApp.theme.colorScheme`.");
lines.push("final ColorScheme wmLightColorScheme = ColorScheme(");
lines.push("  brightness: Brightness.light,");
lines.push("  primary: WMTokens.brand,");
lines.push("  onPrimary: WMTokens.white,");
lines.push("  primaryContainer: WMTokens.brandSoft,");
lines.push("  onPrimaryContainer: WMTokens.brandText,");
lines.push("  secondary: WMTokens.info,");
lines.push("  onSecondary: WMTokens.white,");
lines.push("  secondaryContainer: WMTokens.infoSoft,");
lines.push("  onSecondaryContainer: WMTokens.grey900,");
lines.push("  error: WMTokens.danger,");
lines.push("  onError: WMTokens.white,");
lines.push("  errorContainer: WMTokens.dangerSoft,");
lines.push("  onErrorContainer: WMTokens.grey900,");
lines.push("  surface: WMTokens.white,");
lines.push("  onSurface: WMTokens.grey900,");
lines.push("  surfaceContainerLow: WMTokens.grey50,");
lines.push("  surfaceContainer: WMTokens.grey100,");
lines.push("  outline: WMTokens.grey300,");
lines.push("  outlineVariant: WMTokens.grey200,");
lines.push(");");

const out = lines.join("\n") + "\n";

mkdirSync(outDir, { recursive: true });
writeFileSync(outPath, out);
console.log(`✓ wrote ${outPath} (${out.length} bytes, ${COLOR_KEYS.length} colors)`);
