# Generated by Django 5.1.4 on 2026-05-04 02:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=128, unique=True)),
                ('code_verifier', models.CharField(max_length=128)),
                ('redirect_uri', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oauth_state',
                'indexes': [models.Index(fields=['state'], name='idx_oauth_state_state')],
            },
        ),
        migrations.CreateModel(
            name='OAuthIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=32)),
                ('provider_subject', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'oauth_identity',
                'indexes': [models.Index(fields=['user'], name='idx_oauth_identity_user')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_subject'), name='uniq_oauth_provider_subject')],
            },
        ),
    ]
